# Variables applied to every host in inventory
ansible_become: true
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3

nfs_server: 192.168.50.201
nfs_share: /volume1/networkShare

lab_users:
  - name: home-user
    key: ~/.ssh/home-user.pub

