#cloud-config

users:
  - name: ansible
    groups: wheel
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMgmos9TmIWtM0O+h8EwtXmuDo7tkpXjEBV0g84EcPt0

disable_root: true
ssh_pwauth: false

write_files:
  - path: /etc/ssh/sshd_config.d/99-hardening.conf
    content: |
      PasswordAuthentication no
      PubkeyAuthentication yes
      PermitRootLogin no
    permissions: '0600'

runcmd:
  - systemctl restart sshd
  - systemctl enable --now qemu-guest-agent

final_message: "Cloud-init complete. System ready."