all:
  children:
    proxmox:
      hosts:
        node1.kds-dev.com:
          ansible_host: 192.168.50.101
        node2.kds-dev.com:
          ansible_host: 192.168.50.102
        node3.kds-dev.com:
          ansible_host: 192.168.50.103
    vms:
      children:
        k3s_control:
          hosts:
            ctrl01.kds-dev.com:
            ctrl02.kds-dev.com:
            ctrl03.kds-dev.com:
        k3s_workers:
          hosts:
            work01.kds-dev.com:
            work02.kds-dev.com:
            work03.kds-dev.com:
        mgmt:
          hosts:
            mgmt01.kds-dev.com: