all:
  children:
    proxmox:
      hosts:
        node1.kds-dev.com:
          ansible_host: 192.168.50.101
        node2.kds-dev.com:
          ansible_host: 192.168.50.102
        node3.kds-dev.com:
          ansible_host: 192.168.50.103
    vms:
      children:
        k3s_control:
          hosts:
            ctrl1.kds-dev.com:
              ansible_host: 192.168.50.111
            ctrl2.kds-dev.com:
              ansible_host: 192.168.50.112
            ctrl3.kds-dev.com:
              ansible_host: 192.168.50.113
        k3s_workers:
          hosts:
            work1.kds-dev.com:
              ansible_host: 192.168.50.121
            work2.kds-dev.com:
              ansible_host: 192.168.50.122
            work3.kds-dev.com:
              ansible_host: 192.168.50.123
        tailscale:
          hosts:
            ts1.kds-dev.com:
              ansible_host: 192.168.50.131