---
- name: Include repo configuration tasks
  ansible.builtin.import_tasks: repos.yml

- name: Include package update tasks
  ansible.builtin.import_tasks: updates.yml

- name: Include subscription nag removal tasks
  ansible.builtin.import_tasks: nag.yml

- name: Include hosts file tasks
  ansible.builtin.import_tasks: hosts.yml

- name: Include timezone tasks
  ansible.builtin.import_tasks: timezone.yml

- name: Include NTP tasks
  ansible.builtin.import_tasks: ntp.yml

- name: Include SSH hardening tasks
  ansible.builtin.import_tasks: ssh.yml