---
# NAS connection details
nas_host: "192.168.50.201"
nas_export_base: "/volume1/networkShare"

# NFS storages to configure in Proxmox
pve_nfs_storages:
  - id: vm-disks
    export: "{{ nas_export_base }}/vm-disks"
    content: "images,snippets"
  - id: pve-iso
    export: "{{ nas_export_base }}/pve-iso"
    content: "iso,vztmpl"
