---
title: kds-dev.com
theme: dark
color: slate
headerStyle: clean

background:
  image: /images/background.jpg
  blur: ""
  saturate: 50
  brightness: 90
  opacity: 90

cardBlur: md

layout:
  Infrastructure:
    style: column
    columns: 1
  Apps:
    style: column
    columns: 1
  External:
    style: column
    columns: 1
  Business:
    style: column
    columns: 1

quicklaunch:
  quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  provider: google
  target: _blank