apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-work
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.201
    path: /volume1/networkShare/srv/adguardhome/work