---
proxmox_timezone: "America/Boise"
 
proxmox_debian_release: "trixie"
 
proxmox_nodes:
  - name: node1
    fqdn: node1.kds-dev.com
    ip: 192.168.50.101
  - name: node2
    fqdn: node2.kds-dev.com
    ip: 192.168.50.102
  - name: node3
    fqdn: node3.kds-dev.com
    ip: 192.168.50.103
 
proxmox_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
 