apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.201
    path: /volume1/networkShare/srv/jellyfin/cache