apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: jellyfin-config
  resources:
    requests:
      storage: 10Gi