all:
  children:
    k3s_nodes:
      hosts:
        homenode01:
          ansible_host: 192.168.50.101
        homenode02:
          ansible_host: 192.168.50.102
        homenode03:
          ansible_host: 192.168.50.103
