---
- name: apt update cache
  ansible.builtin.apt:
    update_cache: true

- name: restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted

- name: restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted