---
# Apply baseline configuration to every node
- name: Standard configuration
  hosts: all
  become: true
  roles:
    - standard

# Apply k3s configuration to k3s cluster nodes
- name: k3s configuration
  hosts: k3s_nodes
  become: true
  roles:
    - k3s

