apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v2.6.3
          ports:
            - containerPort: 2283
          env:
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: db-password
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: REDIS_PORT
              value: "6379"
            - name: UPLOAD_LOCATION
              value: /data
            - name: TZ
              value: "America/Boise"
          volumeMounts:
            - name: photos
              mountPath: /data
      volumes:
        - name: photos
          persistentVolumeClaim:
            claimName: immich-photos