apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: immich-postgres
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: immich-photos
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: immich-model-cache
  resources:
    requests:
      storage: 20Gi