# Managed by Ansible
---
- name: Include package tasks
  ansible.builtin.import_tasks: packages.yml

- name: Include timezone tasks
  ansible.builtin.import_tasks: timezone.yml

- name: Include hostname tasks
  ansible.builtin.import_tasks: hostname.yml

- name: Include security tasks
  ansible.builtin.import_tasks: security.yml

- name: Include firewall tasks
  ansible.builtin.import_tasks: firewall.yml
