# Managed by Ansible
---
- name: Run full dnf update
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true

- name: Install baseline packages
  ansible.builtin.dnf:
    name:
      - chrony
      - qemu-guest-agent
    state: present

- name: Enable and start qemu-guest-agent
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true
