# Managed by Ansible
---
- name: Set system timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Deploy chrony configuration
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart chronyd

- name: Enable and start chronyd
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
