# Managed by Ansible
---
pve_ha_rules:
  - name: ha-mgmt
    nodes: "node1:3,node2:2,node3:1"
    strict: 0
    comment: "Managed by Ansible"
    resources:
      - "vm:131"  # ts1 - Tailscale subnet router
