apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-kds-dev-com
  namespace: traefik
spec:
  secretName: wildcard-kds-dev-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.kds-dev.com"
  dnsNames:
    - "*.kds-dev.com"
    - "kds-dev.com"