apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: mealie-data
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-postgres
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: mealie-postgres
  resources:
    requests:
      storage: 5Gi